---
title: "R-Dash"
author: "Justin"
date: "2023-03-12"
output: html_document
---

```{r}

r <- getOption('repos')
r['CRAN'] <- 'http://cloud.r-project.org'
options(repos=r)

# ======================================================================

# packages go here
install.packages(c('readr', 'here', 'ggthemes', 'remotes','dashCoreComponents'))

remotes::install_github("plotly/dashR", upgrade = "always")
remotes::install_github('facultyai/dash-bootstrap-components@r-release')


my_packages = c("randomForest", "data.table")

install_if_missing = function(p) {
  if (p %in% rownames(installed.packages()) == FALSE) {
    install.packages(p)
  }
}

invisible(sapply(my_packages, install_if_missing))
```

```{r}
library(dash)
library(dashCoreComponents)
library(dashHtmlComponents)
library(dashBootstrapComponents)
library(ggplot2)
library(plotly)
library(tidyr)
library(stringr)



app <- Dash$new(external_stylesheets = dbcThemes$BOOTSTRAP)

sleep_df <- read.csv('../data/Sleep_Efficiency.csv')



# binned ages
age_bins = c(0, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, max(sleep_df$Age))
age_bins_labels = c('0-15','15-20','21-25','26-30','31-35','36-40','41-45','46-50','51-55','56-60','60+')
sleep_df$binnedAge = cut(sleep_df$Age, breaks=age_bins, labels=age_bins_labels)
#sleep_df$year <- as.character(sleep_df$year)

#constructing multilist for drop down (year selection) options with label and value
#the years variable is set to the 'options' argument in dccDropdown()
# years <- lapply(
#   unique(sleep_df$year),
#   function(available_indicator) {
#     list(label = available_indicator,
#          value = available_indicator)
#   }
# )


#constructing multilist for drop down (country selection) options with label and value
#the countries variable is set to the 'options' argument in dccDropdown()
# countries <- lapply(
#   unique(sleep_df$Country.Name),
#   function(available_indicator) {
#     list(label = available_indicator,
#          value = available_indicator)
#   }
# )


#########################Sleep DATA#####################
Sleep.efficiency <- lapply(
  unique(sleep_df$Sleep.efficiency),
  function(available_indicator) {
    list(label = available_indicator,
         value = available_indicator)
  }
)
Gender <- lapply(
  unique(sleep_df$Gender),
  function(available_indicator) {
    list(label = available_indicator,
         value = available_indicator)
  }
)
Age <- lapply(
  unique(sleep_df$Age),
  function(available_indicator) {
    list(label = available_indicator,
         value = available_indicator)
  }
)
Sleep.duration <- lapply(
  unique(sleep_df$Sleep.duration),
  function(available_indicator) {
    list(label = available_indicator,
         value = available_indicator)
  }
)
Awakenings <- lapply(
  unique(sleep_df$Awakenings),
  function(available_indicator) {
    list(label = available_indicator,
         value = available_indicator)
  }
)






app$layout(
  dbcContainer(list(
    htmlHr(),
    # filters row
    dbcRow(
      list(
        # side filter column
        dbcCol(
          list(
            htmlBr(),
            htmlH4('Sleep Efficiency Dash'),
            htmlHr(),
            #Home tab sliders
            htmlBr(),
            htmlH5("Control", style = list(
              textAlign = "center"
            )),
            htmlBr(),
            
            
            
            # Cost to Start Slider
            htmlDiv(
              list(
                htmlLabel('Alcohol Consumption (Mg)'),
                dccRangeSlider(
                id='alcoholconsumptioninput',
                min = 0,
                max = 5,
                step = 1,
                value = c(1,3),
                marks = list(
                     "0"="0mg",
                    "1" = "1mg",
                    "2" = "2mg",
                    "3" = "3mg",
                    "4" = "4mg",
                    "5" = "5mg",
                    "6" = "6mg"
                )
            )
            # ,
            
                # 
                # dccRangeSlider(
                #   id='home_cts',
                #   min=0,
                #   max=500,
                #   value = list(0, 500),
                #   marks = list(
                #     "0" = "0",
                #     "100" = "100",
                #     "200" = "200",
                #     "300" = "300",
                #     "400" = "400",
                #     "500" = "500"
                #   ),
                #   tooltip = list(
                #     placement = 'bottom'
                #   )
                # )
              )
            ),
            # Time to Start Slider
            htmlDiv(
              list(
            htmlLabel('Caffeine Consumption (Oz)'),
            dccRangeSlider(
                id='caffeineconsumptioninput',
                min = 0,
                max = 200,
                marks = list(
                    "0" = "0",
                    "25" = "25",
                    "50" = "50",
                    "75" = "75",
                    "100" = "100",
                    "125" = "125",
                    "150" = "150",
                    "175" = "175",
                    "200" = "200"
                ),
                value = c(0,100)
            ))
              # list(
              #   htmlLabel('Time to Start (days)'),
              #   dccRangeSlider(
              #     id='home_tts',
              #     min=0,
              #     max=250,
              #     value = list(0, 250),
              #     marks = list(
              #       "0" = "0",
              #       "60" = "60",
              #       "120" = "120",
              #       "180" = "180",
              #       "250" = "250"
              #     ),
              #     tooltip = list(
              #       placement = 'bottom'
              #     )
              #   )
              # )
            ),
            #Resources tab sliders
            htmlBr(),
            # Average Interest Rate Slider
            htmlDiv(
              list(
            htmlLabel('Exercise Frequency (Days/Week)'),
            dccRangeSlider(
                id='exercisefrequencyinput',
                min = 0,
                max = 5,
                marks = list(
                    "0" = "0",
                    "1" = "1",
                    "2" = "2",
                    "3" = "3",
                    "4" = "4",
                    "5" = "5"
                ),
                value = c(0,3)
            ))
              # list(
              #   htmlLabel('Average Interest Rate (%)'),
              #   dccRangeSlider(
              #     id='resources_air',
              #     min=0,
              #     max=30,
              #     value = list(0, 30),
              #     marks = list(
              #       "0" = "0",
              #       "6" = "6",
              #       "12" = "12",
              #       "18" = "18",
              #       "24" = "24",
              #       "30" = "30"
              #     ),
              #     tooltip = list(
              #       placement = 'bottom'
              #     )
              #   )
              # )
            ),
            htmlH5("Dataset", style = list(
              textAlign = "center"
            )),
            htmlP('The dataset contains information about a group of test subjects and their sleep patterns. Each test subject is identified by a unique "Subject ID" and their age and gender are also recorded. The "Bedtime" and "Wakeup time" features indicate when each subject goes to bed and wakes up each day, and the "Sleep duration" feature records the total amount of time each subject slept in hours. The "Sleep efficiency" feature is a measure of the proportion of time spent in bed that is actually spent asleep. The "REM sleep percentage", "Deep sleep percentage", and "Light sleep percentage" features indicate the amount of time each subject spent in each stage of sleep. The "Awakenings" feature records the number of times each subject wakes up during the night. Additionally, the dataset includes information about each subjects caffeine and alcohol consumption in the 24 hours prior to bedtime, their smoking status, and their exercise frequency.')
          ),
          className = "col-md-3",
          style=list(border = "1px solid #d3d3d3", borderRadius = "10px")
        ),
        # end of side filter column
        # tabs column
        dbcCol(list(
          #Header across tabs
          htmlHr(),
          # # top filters row
          # dbcRow(list(
          #   # top filters portion
          #   dbcCol(
          #     # dropdown for country
          #     dccDropdown(
          #       id = 'countries',
          #       placeholder='Select countries...',
          #       value=list(),
          #       options = countries,
          #       multi = TRUE
          #     )
          #   )
          #   # ,
          #   # dbcCol(
          #   #   # dropdown for years
          #   #   dccDropdown(
          #   #     id = 'years',
          #   #     placeholder= 'Select years...',
          #   #     value=list(),
          #   #     options = years,
          #   #     multi = TRUE
          #   #   )
          #   # )
          #   # end of top filters portion
          # 
          # )),
          
          # end of top filters row
          htmlBr(),
          # tabs row
          dbcRow(list(
            # tabs
            dbcTabs(id = 'tabs', children = list(
              # # Home Tab
              # dbcTab(label = 'Home', children = list(
              #   dbcRow(htmlH5("Geographic Location")),
              #   dbcRow(list(
              #     dbcCol(list(
              #       htmlP('Understanding the geographic location of the country is very important. This helps to know the neighboring countries, ports etc.'), 
              #       dccGraph(
              #         id='hm_map',
              #         style = list(
              #           borderWidth = "0",
              #           width = "100%",
              #           height = "250px"
              #         )
              #       )
              #     ))   
              #   )),
              #   dbcRow(list(
              #     htmlH5("Cost and Time requirements to start a business"),
              #     htmlP("Cost and time factors are very important. Cost tells us how costly interms of a countrie's % of income per capita \
              #                       is required to start a business in the country. Time tells us how many days are required in business starting procedures. \
              #                       Lower the percentage and days, favorable it is for anyone to start a business.")
              #   )),
              #   dbcRow(list(
              #     dbcCol(list(
              #       dccGraph(
              #         id='hm_line',  
              #         style = list(
              #           borderWidth = "0",
              #           width = "100%",
              #           height = "350px"
              #         )
              #       )
              #     ))
              #   ))
              # )),
              # # end of Home tab
              # Resources Tab
              dbcTab(label = 'General Information', children = list(
                 dbcRow(list(
                  dbcCol(list(
                    dccGraph(
                      id='int_line',
                      style = list(
                        borderWidth = "0",
                        width = "100%",
                        height = "500px"
                      )
                    )
                  ))  
                )),
                dbcRow(list(
                  dbcCol(list(
                    dccGraph(
                      id='ur_bar',
                      style = list(
                        borderWidth = "0",
                        width = "100%",
                        height = "500px"
                      )
                    )
                  )),
                  dbcCol(list(
                    dccGraph(
                      id='pr_bar',
                      style = list(
                        borderWidth = "0",
                        width = "100%",
                        height = "500px"
                      )
                    )
                  ))
                ),className="g-0")
                
              )),
              # end of Resources tab
              # Logistics Tab
              dbcTab(label = "Filterable", children = list(
                
                
                
                
                
                
                
                
                # 1st row for bar and radar chart
                dbcRow(list(
                  # multi-bar chart
                  dbcCol(list(
                    dccGraph(
                      id='cc_bar',
                      style = list(
                        borderWidth = "0",
                        width = "100%",
                        height = "300px"
                      )
                    )
                  ))
                )),
                # end of 1st row for bar and radar chart
                # 2nd row for horizontal stacked bar
                dbcRow(list(
                  dccGraph(
                    id='tte_sb',
                    style = list(
                      borderWidth = "0",
                      width = "100%",
                      height = "300px"
                    )
                  )
                )),
                # 3rd row for horizontal stacked bar
                dbcRow(list(
                  dccGraph(
                    id='tti_sb',
                    style = list(
                      borderWidth = "0",
                      width = "100%",
                      height = "300px"
                    )
                  )
                ))
              ))
            ))
            # end of tabs
          ))
          # end of tabs row
        ))
        # end of tabs column
      )
      # end of filters row
    )
  ))
)
# --HOME CALLBACK--

# --RESOURCES CALLBACK--
#Line chart (interest rate)
app$callback(
  output(id = 'int_line', property = 'figure'),
  list(input(id = 'alcoholconsumptioninput', property = 'value'),
       input(id = 'caffeineconsumptioninput', property = 'value'),
       input(id = 'exercisefrequencyinput', property = 'value')),
  
  function(alcoholconsumptioninput,caffeineconsumptioninput,exercisefrequencyinput) {
    series_name <- 'Interest rate spread (lending rate minus deposit rate, %)'
    sleepeffdf = sleep_df %>% 
      filter(
      Alcohol.consumption %in% alcoholconsumptioninput,
      Caffeine.consumption %in% caffeineconsumptioninput,
      Exercise.frequency %in% exercisefrequencyinput
      ) %>%
      select(binnedAge, Sleep.efficiency, Gender) %>%
      group_by(binnedAge) %>% mutate(meansleep = mean(Sleep.efficiency, na.rm = TRUE))
    age_sleepeff_line2 = ggplot(sleepeffdf, aes(x = binnedAge,
                                                y = meansleep,
                                                color = Gender)) + 
        geom_point(size = 5, 
                   color="red") +
        geom_line() +  
        scale_color_manual(values = c('#3493bf', '#c74448')) +
        labs(title = "Sleep efficiency % by Age Group",
             x = "Age Groups",
             y = "Mean Sleep efficiency (%)",
             color = "Gender") +
        theme(axis.title.x = element_text(size = 12), 
        axis.title.y = element_text(size = 12), 
        plot.title = element_text(size = 15, hjust = 0.5),
        axis.text.y = element_text(size = 7),
        axis.text.x = element_text(size = 7)) 
    
    ggplotly(age_sleepeff_line2)
  }
)

#Bar chart (unemployment)
app$callback(
  output(id = 'ur_bar', property = 'figure'),
  list(input(id = 'alcoholconsumptioninput', property = 'value'),
       input(id = 'caffeineconsumptioninput', property = 'value'),
       input(id = 'exercisefrequencyinput', property = 'value')),
  
  function(alcoholconsumptioninput,caffeineconsumptioninput,exercisefrequencyinput) {
    options(repr.plot.width=14, repr.plot.height=6)

    age_sleepdur_bar = 
    ggplot(sleep_df, aes(x = binnedAge, y = Sleep.duration, fill = Gender)) +
    geom_col(position = position_dodge(), width = 0.5) +
    labs(title = "Mean Sleep duration by Age Group" , x = "Binned Age", y = "Mean Sleep Duration", fill = "Gender") +
    scale_color_manual(values = c('#3493bf', '#c74448')) +
    theme(axis.title.x = element_text(size = 12), 
        axis.title.y = element_text(size = 12), 
        plot.title = element_text(size = 15, hjust = 0.5),
        axis.text.y = element_text(size = 7),
        axis.text.x = element_text(size = 7))  
    
    ggplotly(age_sleepdur_bar)

  }
)

#Bar chart (participation)
app$callback(
  output(id = 'pr_bar', property = 'figure'),
  list(input(id = 'alcoholconsumptioninput', property = 'value'),
       input(id = 'caffeineconsumptioninput', property = 'value'),
       input(id = 'exercisefrequencyinput', property = 'value')),
  
  function(alcoholconsumptioninput,caffeineconsumptioninput,exercisefrequencyinput) {
    awakening_bar = 
ggplot(sleep_df, aes(x = factor(Awakenings), fill = Gender)) +
geom_bar() +
coord_flip() +
labs(title = "Count of awakenings", x = "Number of Awakenings", y = "", fill = "Gender") +
scale_color_manual(values = c('#3493bf', '#c74448')) +
theme(axis.title.x = element_text(size = 12), 
        axis.title.y = element_text(size = 12), 
        plot.title = element_text(size = 15, hjust = 0.5),
        axis.text.y = element_text(size = 7),
        axis.text.x = element_text(size = 7)) 
ggplotly(awakening_bar)
  }
  
)


app$callback(
  output(id = 'cc_bar', property = 'figure'),
  list(input(id = 'alcoholconsumptioninput', property = 'value'),
       input(id = 'caffeineconsumptioninput', property = 'value'),
       input(id = 'exercisefrequencyinput', property = 'value')),

function(alcoholconsumptioninput,caffeineconsumptioninput,exercisefrequencyinput) {
  
  thisdata = sleep_df %>% 
    select(REM.sleep.percentage, Gender) %>%
    mutate(REM.sleep.bin = cut(sleep_df$REM.sleep.percentage, breaks = 10, include.lowest = FALSE))
  
    REMplot = ggplot(thisdata, aes(x = REM.sleep.bin, fill = Gender)) +
geom_bar() +
coord_flip() +
labs(x = "REM Sleep %", 
     y = "", 
     title = "Counts\n") +
scale_color_manual(values = c('#3493bf', '#c74448')) +
theme(axis.title.x = element_text(size = 25), 
axis.title.y = element_text(size = 25), 
plot.title = element_text(size = 30, hjust = 0.5),
axis.text.y = element_text(size = 14),
axis.text.x = element_text(angle = 90, vjust = 0.5, size = 14)) 

ggplotly(REMplot)
  }
  
)

app$callback(
  output(id = 'tte_sb', property = 'figure'),
  list(input(id = 'alcoholconsumptioninput', property = 'value'),
       input(id = 'caffeineconsumptioninput', property = 'value'),
       input(id = 'exercisefrequencyinput', property = 'value')),
  
  function(alcoholconsumptioninput,caffeineconsumptioninput,exercisefrequencyinput) {
  
  thisdata = sleep_df %>% 
    select(Deep.sleep.percentage, Gender) %>%
    mutate(Deep.sleep.bin = cut(sleep_df$Deep.sleep.percentage, breaks = 10, include.lowest = FALSE))
  
    REMplot = ggplot(thisdata, aes(x = Deep.sleep.bin, fill = Gender)) +
geom_bar() +
coord_flip() +
labs(x = "REM Sleep %", 
     y = "", 
     title = "Counts\n") +
scale_color_manual(values = c('#3493bf', '#c74448')) +
theme(axis.title.x = element_text(size = 25), 
axis.title.y = element_text(size = 25), 
plot.title = element_text(size = 30, hjust = 0.5),
axis.text.y = element_text(size = 14),
axis.text.x = element_text(angle = 90, vjust = 0.5, size = 14)) 

ggplotly(REMplot)
  }
  
)

app$callback(
  output(id = 'tti_sb', property = 'figure'),
  list(input(id = 'alcoholconsumptioninput', property = 'value'),
       input(id = 'caffeineconsumptioninput', property = 'value'),
       input(id = 'exercisefrequencyinput', property = 'value')),
  
  function(alcoholconsumptioninput,caffeineconsumptioninput,exercisefrequencyinput) {
  
  thisdata = sleep_df %>% 
    select(Light.sleep.percentage, Gender) %>%
    mutate(Light.sleep.bin = cut(sleep_df$Light.sleep.percentage, breaks = 10, include.lowest = FALSE))
  
    REMplot = ggplot(thisdata, aes(x = Light.sleep.bin, fill = Gender)) +
geom_bar() +
coord_flip() +
labs(x = "REM Sleep %", 
     y = "", 
     title = "Counts\n") +
scale_color_manual(values = c('#3493bf', '#c74448')) +
theme(axis.title.x = element_text(size = 25), 
axis.title.y = element_text(size = 25), 
plot.title = element_text(size = 30, hjust = 0.5),
axis.text.y = element_text(size = 14),
axis.text.x = element_text(angle = 90, vjust = 0.5, size = 14)) 

ggplotly(REMplot)
  }
  
)
# app$callback(
#   output(id = 'cc_bar', property = 'figure'),
#   list(input(id = 'alcoholconsumptioninput', property = 'value'),
#        input(id = 'caffeineconsumptioninput', property = 'value'),
#        input(id = 'exercisefrequencyinput', property = 'value')),
#   
#   function(alcoholconsumptioninput,caffeineconsumptioninput,exercisefrequencyinput) {
#     options(repr.plot.width=14, repr.plot.height=6)
# 
#     thisdata = sleep_df %>% 
#     select(Light.sleep.percentage, Gender) %>%
#     mutate(Light.sleep.bin = cut(sleep_df$Light.sleep.percentage, breaks = 10, include.lowest = FALSE)) %>%
#     filter( Alcohol.consumption %in% alcoholconsumptioninput,
#             Caffeine.consumption %in% caffeineconsumptioninput,
#             Exercise.frequency %in% exercisefrequencyinput)
#       
#     rs_bar = ggplot(thisdata, aes(x = REM.sleep.bin, fill = Gender)) +
#     geom_bar() +
#     coord_flip() +
#     labs(x = "REM Sleep %", 
#          y = "", 
#          title = "Counts\n") +
#     scale_color_manual(values = c('#3493bf', '#c74448')) +
#     theme(axis.title.x = element_text(size = 25), 
#     axis.title.y = element_text(size = 25), 
#     plot.title = element_text(size = 30, hjust = 0.5),
#     axis.text.y = element_text(size = 14),
#     axis.text.x = element_text(angle = 90, vjust = 0.5, size = 14)) 
#     
#     ggplotly(rs_bar)
# 
#   }
# )

app$run_server(debug = T)

```


